import type { Metadata } from "next";
import Link from "next/link";
import {
  ArrowRight, BarChart3, BellRing, Bot, Building2, CalendarCheck, Check, ChevronRight,
  ClipboardCheck, Cloud, FileCheck2, FileClock, FolderLock, HandHeart, HeartHandshake,
  Landmark, Languages, LayoutDashboard, LockKeyhole, Network, ShieldCheck, Sparkles,
  UsersRound, Workflow, UserCog, SlidersHorizontal, Activity, KeyRound,
} from "lucide-react";
import "./marketing.css";
import MarketingEffects from "@/components/marketing-effects";
import PublicNavigation from "@/components/public-navigation";
import { getLocale, getTranslations, getFormatter } from "next-intl/server";
import { getPublicLocalizationSettings } from "@/i18n/public-settings";
import { getServerBrand } from "@/branding/server";
import { BrandIdentity } from "@/branding/client";

export async function generateMetadata(): Promise<Metadata> {
  const t = await getTranslations("Marketing");
  const brand = await getServerBrand(await getLocale());
  return {
    title: { absolute: brand.enabled ? brand.product_name : t("setuNgoComplianceAndImpactManagementPlatform", {brand: brand.brand_name}) },
    description: brand.enabled ? brand.description : t("manageNgoComplianceDeadlinesEvidenceTasksDonorsGrantsCsr"),
  };
}

export default async function MarketingHome() {
  const [t, format, locale, localization] = await Promise.all([
    getTranslations("Marketing"), getFormatter(), getLocale(), getPublicLocalizationSettings(),
  ]);
  const brand = await getServerBrand(locale);
const coreServices = [
  { icon: ClipboardCheck, title: t("complianceOperations"), text: t("planObligationsAssignAccountableOwnersTrackStatutoryAndInternal") },
  { icon: CalendarCheck, title: t("calendarAndAutomation"), text: t("seeUpcomingOverdueAndRecurringObligationsWithRemindersEscalation") },
  { icon: FolderLock, title: t("evidenceAndDocuments"), text: t("keepCategorizedEvidenceLinkedToEachObligationWithImmutable") },
  { icon: Workflow, title: t("tasksAndApprovals"), text: t("turnEveryObligationIntoClearWorkChecklistsAssigneesPriorities") },
  { icon: BarChart3, title: t("dashboardsAndReports"), text: t("understandPortfolioHealthOwnerWorkloadOverdueExposureAndUpcoming") },
  { icon: UsersRound, title: t("teamsAndPermissions"), text: t("inviteAdministratorsComplianceOfficersAccountantsAuditorsConsultantsManagementAnd") },
];

const steps = [
  ["01", t("setUpTheOrganization"), t("captureLegalStructureRegistrationIdentifiersStatusAndApplicabilityAttributes")],
  ["02", t("generateTheCompliancePlan"), t("applyVersionedCatalogueRulesAndReviewCandidateObligationsBefore")],
  ["03", t("assignAndPrepare"), t("setOwnersInternalTargetsTasksCommentsAndEvidenceRequirements")],
  ["04", t("reviewAndFile"), t("requestCorrectionsApproveWorkRecordAcknowledgementDetailsAndPreserve")],
  ["05", t("reportAndRollForward"), t("auditTheLifecycleMonitorRiskAndCreateTheNext")],
];

const plans = [
  { name: t("starter"), audience: t("forASingleNgoEstablishingAControlledComplianceProcess"), features: [t("coreComplianceRegister"), t("tasksAndEvidence"), t("calendarAndDashboard"), t("standardReports")] },
  { name: t("professional"), audience: t("forGrowingOrganizationsThatNeedMoreUsersAndAutomation"), features: [t("everythingInStarter"), t("expandedTeamCapacity"), t("automatedReminders"), t("advancedReportingFoundation")], featured: true },
  { name: t("business"), audience: t("forConsultantsAndTeamsManagingMultipleOrganizations"), features: [t("everythingInProfessional"), t("multiOrganizationPortfolio"), t("impactAndDDModules"), t("integrationManagement")] },
  { name: t("enterprise"), audience: t("forLargeOrRegulatedDeploymentsRequiringTailoredControls"), features: [t("customLimitsAndControls"), t("ssoAndSecurityRoadmap"), t("serviceLevelOptions"), t("whiteLabelFoundation")] },
];

const certificateFeatures = [
  { icon: FileCheck2, title: t("registrationCertificates"), text: t("organizeTrustSocietySection8Pan12a80gAnd") },
  { icon: CalendarCheck, title: t("renewalVisibility"), text: t("recordIssueAndExpiryDatesAccountableOwnersInternalTargets") },
  { icon: FolderLock, title: t("versionedProof"), text: t("preserveReplacementCertificatesAndSupportingEvidenceWithoutLosingHistorical") },
];

const projectFeatures = [
  { icon: HandHeart, label: t("csrProjects"), title: t("deliveryAndMilestoneTracking"), text: t("connectProjectOwnershipDeliveryStatusDueDatesAndGovernance") },
  { icon: HeartHandshake, label: t("grants"), title: t("commitmentsAndUtilization"), text: t("keepGrantConditionsRestrictedPurposeContextAndUtilizationReporting") },
  { icon: UsersRound, label: t("volunteers"), title: t("programmesAndParticipation"), text: t("maintainResponsibleOwnersActivityRecordsAndTimeBoundProgramme") },
];


  return <main className="marketing-site">
    <MarketingEffects />
    <PublicNavigation localization={localization} />

    <section className="marketing-hero" id="home">
      <div className="hero-atmosphere" aria-hidden="true"><i /><i /><i /></div>
      <div className="hero-copy"><span className="marketing-kicker"><Sparkles size={15} /><span>{t("builtForNgosAndComplianceProfessionals")}</span></span><h1><span>{t("everyObligation")}</span><br /><em>{t("oneClearPathToCompletion")}</em></h1><p>{t("setuBringsComplianceSchedulesTeamResponsibilitiesEvidenceDonorRelationships", {brand: brand.brand_name})}</p><div className="hero-actions"><Link className="marketing-button hero-primary" href="/signup"><span>{t("createYourWorkspace")}</span> <ArrowRight size={17} /></Link><a className="marketing-button ghost hero-secondary" href="#platform"><span>{t("exploreThePlatform")}</span> <ChevronRight size={17} /></a></div><div className="hero-assurance"><span><Check size={15} /><span>{t("tenantIsolatedRecords")}</span></span><span><Check size={15} /><span>{t("auditableWorkflows")}</span></span><span><Check size={15} /><span>{t("indiaFirstConfiguration")}</span></span></div><div className="hero-proof"><article><strong>{t("oneView")}</strong><small>{t("complianceEvidenceAndImpact")}</small></article><article><strong>{t("clearOwnership")}</strong><small>{t("everyTaskHasAccountability")}</small></article><article><strong>{t("auditReady")}</strong><small>{t("historyStaysTraceable")}</small></article></div></div>
      <div className="product-preview" aria-label={t("exampleComplianceDashboard")}>
        <div className="preview-signal"><span><Activity size={15} /></span><div><small>{t("liveControl")}</small><strong>{t("86PortfolioOnTrack", {progress: format.number(0.86, {style: "percent"})})}</strong></div><i /></div>
        <div className="preview-top"><span className="preview-logo"><ShieldCheck size={16} /></span><i /><i /><b>{t("portfolioOverview")}</b><span className="preview-avatar">AD</span></div>
        <div className="preview-body"><aside><i className="active"><LayoutDashboard size={15} /></i><i><ClipboardCheck size={15} /></i><i><CalendarCheck size={15} /></i><i><FolderLock size={15} /></i><i><BarChart3 size={15} /></i></aside><div className="preview-content"><div className="preview-heading"><div><small>{t("goodMorning")}</small><strong>{t("yourComplianceControlRoom")}</strong></div><span>{t("allOrganizations")}</span></div><div className="preview-metrics"><article><small>{t("activeObligations")}</small><strong>{format.number(48)}</strong><em>{t("acrossThePortfolio")}</em></article><article><small>{t("needsAttention")}</small><strong>{format.number(7, {minimumIntegerDigits: 2})}</strong><em>{t("ownersNotified")}</em></article><article><small>{t("onTrack")}</small><strong>{format.number(0.86, {style: "percent"})}</strong><em>{t("currentCycle")}</em></article></div><div className="preview-grid"><article className="preview-deadlines"><header><strong>{t("priorityDeadlines")}</strong><span>{t("viewAll")}</span></header>{[[t("fcraAnnualReturn"), t("high"), format.dateTime(new Date("2026-12-31T12:00:00Z"), {day: "numeric", month: "short", timeZone: "Asia/Kolkata"})], [t("annualAudit"), t("review"), format.dateTime(new Date("2026-09-30T12:00:00Z"), {day: "numeric", month: "short", timeZone: "Asia/Kolkata"})], [t("80gRenewalEvidence"), t("medium"), format.dateTime(new Date("2026-11-30T12:00:00Z"), {day: "numeric", month: "short", timeZone: "Asia/Kolkata"})]].map((row) => <div key={row[0]}><i /><span><strong>{row[0]}</strong><small>{t("evidenceAndOwnerTracked")}</small></span><b>{row[1]}</b><em>{row[2]}</em></div>)}</article><article className="preview-health"><header><strong>{t("portfolioHealth")}</strong></header><div className="health-ring"><span>{format.number(0.86, {style: "percent"})}</span></div><p>{t("complianceCompletion")}</p><footer><span><i />{t("complete")}</span><span><i />{t("inProgress")}</span><span><i />{t("atRisk")}</span></footer></article></div></div></div>
        <div className="preview-float preview-float-evidence"><FileCheck2 size={16} /><span><small>{t("evidenceCheck")}</small><strong>{t("auditTrailComplete")}</strong></span><Check size={14} /></div>
        <div className="preview-float preview-float-deadline"><BellRing size={15} /><span><small>{t("nextDeadline")}</small><strong>{t("ownerNotifiedEarly")}</strong></span></div>
      </div>
    </section>

    <section className="trust-strip"><span>{t("designedFor")}</span><strong><Building2 size={18} />{t("trusts")}</strong><strong><Landmark size={18} />{t("societies")}</strong><strong><FileCheck2 size={18} />{t("section8Companies")}</strong><strong><UsersRound size={18} />{t("caAndConsultantFirms")}</strong></section>

    <section className="marketing-section intro" id="platform"><div className="section-heading"><span>{t("thePlatform")}</span><h2>{t("aConnectedOperatingSystemForComplianceWork")}</h2><p>{t("setuFollowsTheFullOperationalLifecycleFromApplicabilityAnd", {brand: brand.brand_name})}</p></div><div className="service-grid">{coreServices.map(({ icon: Icon, title, text }) => <article key={title}><span><Icon size={22} /></span><h3>{title}</h3><p>{text}</p><a href="#workflow">{t("seeHowItWorks")}<ArrowRight size={14} /></a></article>)}</div></section>

    <section className="certificate-section" id="certificates"><div className="section-heading"><span>{t("certificatesAndRegistrations")}</span><h2>{t("knowWhatIsValidWhatIsExpiringAndWhere")}</h2><p>{t("setuDoesNotIssueGovernmentCertificatesItGivesYour", {brand: brand.brand_name})}</p></div><div className="certificate-grid">{certificateFeatures.map(({ icon: Icon, title, text }, index) => <article key={title}><b>0{index + 1}</b><span><Icon size={22} /></span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="certificate-assurance"><ShieldCheck size={18} /><span><strong>{t("evidenceNotLegalIssuance")}</strong>{t("certificateDataRemainsOrganizationScopedPermissionControlledAndConnected")}</span><a href="#security">{t("reviewSecurity")}<ArrowRight size={14} /></a></div></section>

    <section className="workflow-section" id="workflow"><div className="workflow-copy"><span>{t("fromRequirementToRecord")}</span><h2>{t("aWorkflowYourWholeTeamCanFollow")}</h2><p>{t("keepTheStatutoryDeadlineIntactWhileYourTeamWorks")}</p><div className="workflow-note"><BellRing size={21} /><div><strong>{t("attentionBeforeEscalation")}</strong><p>{t("dailyAutomationIdentifiesUpcomingWorkOverdueTasksExpiringDocuments")}</p></div></div></div><ol>{steps.map(([number, title, text]) => <li key={number}><b>{number}</b><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></section>

    <section className="dnd-section" id="dnd"><div className="dnd-visual"><span className="orbit one"><HeartHandshake size={24} /></span><span className="orbit two"><HandHeart size={22} /></span><span className="orbit three"><FileClock size={22} /></span><div><small>{t("connectedImpactRecords")}</small><strong>{t("donor")}</strong><strong>{t("donation")}</strong><strong>{t("reporting")}</strong></div></div><div className="dnd-copy"><span>{t("dDManagement")}</span><h2>{t("donorAndDonationContextBesideCompliance")}</h2><p>{t("trackDonorRelationshipsGrantCommitmentsRestrictedPurposeContextMilestones")}</p><ul><li><Check size={16} /><span><strong>{t("donorRelationshipRecords")}</strong>{t("maintainInstitutionalOrIndividualDonorContextOwnershipAndStewardship")}</span></li><li><Check size={16} /><span><strong>{t("grantAndDonationObligations")}</strong>{t("connectCommitmentsUtilizationReportingAndEvidenceDeadlinesToAccountable")}</span></li><li><Check size={16} /><span><strong>{t("impactPortfolioVisibility")}</strong>{t("reviewGrantsCsrProjectsAndVolunteerProgrammesWithoutMixing")}</span></li></ul><p className="scope-note"><ShieldCheck size={16} />{t("setuManagesOperationalRecordsAndEvidencePaymentCollectionRequires", {brand: brand.brand_name})}</p></div></section>

    <section className="project-section" id="projects"><div className="project-intro"><span>{t("projectAndProgrammeOperations")}</span><h2>{t("fromFundingCommitmentToAccountableDelivery")}</h2><p>{t("bringProjectsIntoTheSameControlledWorkspaceAsCompliance")}</p><Link className="marketing-button" href="/signup">{t("buildYourProjectWorkspace")}<ArrowRight size={16} /></Link></div><div className="project-grid">{projectFeatures.map(({ icon: Icon, label, title, text }, index) => <article key={label}><header><span><Icon size={19} /></span><small>{label}</small><b>0{index + 1}</b></header><h3>{title}</h3><p>{text}</p><i><b style={{ width: `${72 + index * 7}%` }} /></i><footer><span>{t("exampleProgress", {progress: format.number((72 + index * 7) / 100, {style: "percent"})})}</span><strong>{t("ownerTracked")}</strong></footer></article>)}</div></section>

    <section className="marketing-section solutions" id="solutions"><div className="section-heading"><span>{t("whoSetuServes", {brand: brand.brand_name})}</span><h2>{t("onePlatformDifferentViewsOfResponsibility")}</h2></div><div className="solution-grid"><article><Building2 size={26} /><h3>{t("ngos")}</h3><p>{t("replaceDisconnectedRegistersWithAClearComplianceCalendarEvidence")}</p></article><article><Network size={26} /><h3>{t("caAndConsultingFirms")}</h3><p>{t("switchSafelyBetweenClientOrganizationsAndMonitorPortfolioRisk")}</p></article><article><FileCheck2 size={26} /><h3>{t("auditorsAndReviewers")}</h3><p>{t("traceEvidenceVersionsCorrectionRequestsCompletionHistoryAndFiling")}</p></article><article><HandHeart size={26} /><h3>{t("csrAndProgrammeTeams")}</h3><p>{t("keepProjectMilestonesGrantsDonorsAndVolunteerActivityConnected")}</p></article></div></section>

    <section className="capability-band"><div><span>{t("coreToday")}</span><h2>{t("everythingNeededToRunTheComplianceCycle")}</h2><p>{t("organizationsCatalogueRulesObligationsTasksDocumentsNotificationsAuditReports")}</p></div><div><span>{t("readyToConnect")}</span><h2>{t("advancedServicesBehindCleanBoundaries")}</h2><p>{t("emailWhatsappCalendarsCloudDrivesDigitalSignaturesOcrGrounded")}</p></div></section>

    <section className="admin-section" id="admin"><div className="admin-copy"><span>{t("administrationControlCentre")}</span><h2>{t("configureTheWorkspaceWithoutLosingOperationalControl")}</h2><p>{t("theProtectedAdminPortalBringsWorkspaceGovernanceOrganizationSetup")}</p><div className="admin-capabilities"><article><UserCog size={19} /><div><strong>{t("usersAndAccess")}</strong><small>{t("inviteAccountsAssignAdminMemberOrViewerAccessDisable")}</small></div></article><article><Building2 size={19} /><div><strong>{t("organizationsAndResponsibilities")}</strong><small>{t("onboardLegalEntitiesManagePortfolioCapacityAndScopeResponsibility")}</small></div></article><article><SlidersHorizontal size={19} /><div><strong>{t("rulesPlansAndIntegrations")}</strong><small>{t("reviewVersionedCatalogueRulesEntitlementUsageAndProviderConnection")}</small></div></article><article><Activity size={19} /><div><strong>{t("automationAndAudit")}</strong><small>{t("runIdempotentDailyOperationsAndRetainTraceableRecordsOf")}</small></div></article></div><Link className="marketing-button" href="/admin/login"><KeyRound size={16} />{t("openAdminPortal")}<ArrowRight size={16} /></Link></div><div className="admin-preview" aria-label={t("exampleAdminControlCentre")}><header><span><ShieldCheck size={16} />{t("administration")}</span><b>{t("businessPlan")}</b></header><div className="admin-preview-metrics"><article><small>{t("organizations")}</small><strong>{format.number(3)} / {format.number(10)}</strong><i><b style={{ width: "30%" }} /></i></article><article><small>{t("teamAccounts")}</small><strong>{format.number(8)} / {format.number(25)}</strong><i><b style={{ width: "32%" }} /></i></article><article><small>{t("activeRules")}</small><strong>{format.number(14)}</strong><em>{t("versionControlled")}</em></article></div><section><div><strong>{t("userManagement")}</strong><span>{t("inviteUser")}</span></div>{[["Ananya Desai", t("administrator"), t("active")], ["Riya Mehta", t("teamMember"), t("active")], [t("auditReviewer"), t("readOnlyViewer"), t("invited")]].map((row) => <article key={row[0]}><i>{row[0].split(" ").map((part) => part[0]).join("").slice(0, 2)}</i><span><strong>{row[0]}</strong><small>{t("workspaceAccount")}</small></span><b>{row[1]}</b><em>{row[2]}</em></article>)}</section><footer><ShieldCheck size={14} />{t("administrativeActionsArePermissionControlledAndAudited")}</footer></div></section>

    <section className="security-section" id="security"><div><span>{t("securityByDesign")}</span><h2>{t("yourOrganizationBoundaryIsEnforcedOnTheServer")}</h2><p>{t("setuTreatsTheTenantAsTheSecurityAndBilling", {brand: brand.brand_name})}</p><div className="security-list"><span><LockKeyhole size={18} />{t("strongSessionsAndProtectedMutations")}</span><span><ShieldCheck size={18} />{t("roleBasedTenantScopedAccess")}</span><span><FolderLock size={18} />{t("versionedEvidenceMetadata")}</span><span><Cloud size={18} />{t("privateStorageProductionPath")}</span></div></div><aside><Bot size={26} /><h3>{t("humanReviewedIntelligence")}</h3><p>{t("theAssistantSummarizesAuthorizedOperationalRecordsCitesTheRecords")}</p><strong>{t("assistanceWithAccountability")}</strong></aside></section>

    <section className="marketing-section plans" id="plans"><div className="section-heading"><span>{t("plansThatScaleWithResponsibility")}</span><h2>{t("startFocusedAddCapacityWhenYouNeedIt")}</h2><p>{t("planEntitlementsGovernOrganizationsUsersStorageAndAdvancedCapabilities")}</p></div><div className="plan-grid">{plans.map((plan) => <article className={plan.featured ? "featured" : ""} key={plan.name}>{plan.featured && <span className="plan-tag">{t("mostPopular")}</span>}<h3>{plan.name}</h3><p>{plan.audience}</p><ul>{plan.features.map((feature) => <li key={feature}><Check size={15} />{feature}</li>)}</ul><Link href="/signup">{t("choose", {name: plan.name})}<ArrowRight size={15} /></Link></article>)}</div><p className="pricing-note">{t("commercialPricingUsageLimitsAndProviderChargesAreConfigured")}</p></section>

    <section className="faq-section" id="faq"><div className="section-heading"><span>{t("commonQuestions")}</span><h2>{t("whatOrganizationsAskBeforeTheyBegin")}</h2></div><div className="faq-grid"><details open><summary>{t("doesSetuFileDirectlyWithGovernmentPortals", {brand: brand.brand_name})}</summary><p>{t("notByDefaultSetuManagesTheWorkflowEvidenceAnd", {brand: brand.brand_name})}</p></details><details><summary>{t("canAConsultantManageMultipleNgoClients")}</summary><p>{t("yesConsultantWorkspacesCanContainMultipleOrganizationsWithOrganization")}</p></details><details><summary>{t("areComplianceDatesGuaranteedLegalAdvice")}</summary><p>{t("noCatalogueRulesAndDatesAreVersionedConfigurationAnd")}</p></details><details><summary>{t("doesDDIncludePaymentCollection")}</summary><p>{t("dDCoversDonorGrantDonationContextAndReporting")}</p></details><details><summary>{t("canSetuSupportRegionalLanguages", {brand: brand.brand_name})}</summary><p>{t("thePlatformArchitectureSupportsAMultilingualRoadmapEnglishIs")}</p></details><details><summary>{t("whatHappensWhenASubscriptionChanges")}</summary><p>{t("planLimitsAndFeatureAccessCanChangeButHistorical")}</p></details></div></section>

    <section className="support-section" id="support"><div><span>{t("supportTheMission")}</span><h2>{t("helpMoreNgosMoveFromMissedFollowUpsTo")}</h2></div><div className="support-options"><article><strong>{t("partnerWithSetu", {brand: brand.brand_name})}</strong><p>{t("bringImplementationComplianceOrTechnologyExpertiseToOrganizationsThat")}</p><a href="#contact">{t("discussAPartnership")}<ArrowRight size={14} /></a></article><article><strong>{t("referAnOrganization")}</strong><p>{t("introduceAnNgoOrProfessionalPracticeThatIsReady")}</p><Link href="/signup">{t("createTheirWorkspace")}<ArrowRight size={14} /></Link></article><article><strong>{t("contributeExpertise")}</strong><p>{t("helpValidateCatalogueRulesAndOperationalGuidanceBeforeThey")}</p><a href="#contact">{t("startAConversation")}<ArrowRight size={14} /></a></article></div></section>

    <section className="final-cta" id="contact"><span><Languages size={19} />{t("contactAndOnboarding")}</span><h2>{t("giveEveryComplianceResponsibilityAClearOwnerDeadlineAnd")}</h2><p>{t("createAWorkspaceToBeginOnboardingOrSignIn")}</p><div><Link className="marketing-button light" href="/signup">{t("requestOnboarding")}<ArrowRight size={17} /></Link><Link className="marketing-button outline-light" href="/login">{t("logInToSetu", {brand: brand.brand_name})}</Link></div></section>

    <footer className="marketing-footer"><div><Link className="marketing-brand" href="/">{brand.enabled ? <BrandIdentity /> : <><span><ShieldCheck size={21} /></span><strong>Setu NGO<small>{t("complianceAndImpactManagement")}</small></strong></>}</Link><p>{brand.enabled ? brand.description : t("operationalSoftwareForNgoComplianceTeamsAndProfessionalService")}</p>{brand.support_email && <a href={`mailto:${brand.support_email}`}>{brand.support_email}</a>}{brand.support_phone && <p>{brand.support_phone}</p>}{brand.support_url && <a href={brand.support_url} target="_blank" rel="noopener noreferrer">{t("support")}</a>}</div><div><strong>{t("platform")}</strong><a href="#platform">{t("compliance")}</a><a href="#dnd">{t("dD")}</a><a href="#admin">{t("administration")}</a><a href="#security">{t("security")}</a><a href="#plans">{t("plans")}</a></div><div><strong>{t("access")}</strong><Link href="/login">{t("teamLogin")}</Link><Link href="/admin/login">{t("adminLogin")}</Link><Link href="/signup">{t("createWorkspace")}</Link><Link href="/dashboard">{t("openDashboard")}</Link></div><div><strong>{t("important")}</strong><p>{t("supportsComplianceOperationsItDoesNotReplaceACa", {brand: brand.brand_name})}</p>{brand.privacy_url && <a href={brand.privacy_url} target="_blank" rel="noopener noreferrer">{t("privacy")}</a>}{brand.terms_url && <a href={brand.terms_url} target="_blank" rel="noopener noreferrer">{t("terms")}</a>}</div><small>{brand.footer_text || t("copyright", {year: 2026, brand: brand.brand_name})}</small></footer>
  </main>;
}
