import type { Metadata } from "next";
import Link from "next/link";
import {
  ArrowRight, BarChart3, BellRing, Bot, Building2, CalendarCheck, Check, ChevronRight,
  ClipboardCheck, Cloud, FileCheck2, FileClock, FolderLock, HandHeart, HeartHandshake,
  Landmark, Languages, LayoutDashboard, LockKeyhole, Network, ShieldCheck, Sparkles,
  UsersRound, Workflow, UserCog, SlidersHorizontal, Activity, KeyRound,
} from "lucide-react";
import "./marketing.css";
import MarketingEffects from "@/components/marketing-effects";
import MarketingLanguage from "@/components/marketing-language";
import PublicNavigation from "@/components/public-navigation";
import { getLocale } from "next-intl/server";
import { getServerBrand } from "@/branding/server";
import { BrandIdentity } from "@/branding/client";

export async function generateMetadata(): Promise<Metadata> {
  const brand = await getServerBrand(await getLocale());
  return {
    title: { absolute: brand.enabled ? brand.product_name : "Setu NGO | Compliance and Impact Management Platform" },
    description: brand.enabled ? brand.description : "Manage NGO compliance, deadlines, evidence, tasks, donors, grants, CSR projects and reporting in one secure workspace.",
  };
}

const coreServices = [
  { icon: ClipboardCheck, title: "Compliance operations", text: "Plan obligations, assign accountable owners, track statutory and internal dates, review evidence and record filing proof." },
  { icon: CalendarCheck, title: "Calendar and automation", text: "See upcoming, overdue and recurring obligations with reminders, escalation-ready alerts and document-expiry tracking." },
  { icon: FolderLock, title: "Evidence and documents", text: "Keep categorized evidence linked to each obligation with immutable version history, expiry dates and auditable access metadata." },
  { icon: Workflow, title: "Tasks and approvals", text: "Turn every obligation into clear work: checklists, assignees, priorities, correction requests, exceptions and recovery plans." },
  { icon: BarChart3, title: "Dashboards and reports", text: "Understand portfolio health, owner workload, overdue exposure and upcoming deadlines across one NGO or many clients." },
  { icon: UsersRound, title: "Teams and permissions", text: "Invite administrators, compliance officers, accountants, auditors, consultants, management and read-only stakeholders." },
];

const steps = [
  ["01", "Set up the organization", "Capture legal structure, registration identifiers, status and applicability attributes."],
  ["02", "Generate the compliance plan", "Apply versioned catalogue rules and review candidate obligations before activation."],
  ["03", "Assign and prepare", "Set owners, internal targets, tasks, comments and evidence requirements."],
  ["04", "Review and file", "Request corrections, approve work, record acknowledgement details and preserve proof."],
  ["05", "Report and roll forward", "Audit the lifecycle, monitor risk and create the next recurring cycle without rewriting history."],
];

const plans = [
  { name: "Starter", audience: "For a single NGO establishing a controlled compliance process.", features: ["Core compliance register", "Tasks and evidence", "Calendar and dashboard", "Standard reports"] },
  { name: "Professional", audience: "For growing organizations that need more users and automation.", features: ["Everything in Starter", "Expanded team capacity", "Automated reminders", "Advanced reporting foundation"], featured: true },
  { name: "Business", audience: "For consultants and teams managing multiple organizations.", features: ["Everything in Professional", "Multi-organization portfolio", "Impact and D&D modules", "Integration management"] },
  { name: "Enterprise", audience: "For large or regulated deployments requiring tailored controls.", features: ["Custom limits and controls", "SSO and security roadmap", "Service-level options", "White-label foundation"] },
];

const certificateFeatures = [
  { icon: FileCheck2, title: "Registration certificates", text: "Organize trust, society, Section 8, PAN, 12A, 80G and other registration evidence by organization." },
  { icon: CalendarCheck, title: "Renewal visibility", text: "Record issue and expiry dates, accountable owners, internal targets and advance renewal reminders." },
  { icon: FolderLock, title: "Versioned proof", text: "Preserve replacement certificates and supporting evidence without losing historical versions or audit context." },
];

const projectFeatures = [
  { icon: HandHeart, label: "CSR PROJECTS", title: "Delivery and milestone tracking", text: "Connect project ownership, delivery status, due dates and governance evidence." },
  { icon: HeartHandshake, label: "GRANTS", title: "Commitments and utilization", text: "Keep grant conditions, restricted-purpose context and utilization reporting together." },
  { icon: UsersRound, label: "VOLUNTEERS", title: "Programmes and participation", text: "Maintain responsible owners, activity records and time-bound programme obligations." },
];

export default async function MarketingHome() {
  const brand = await getServerBrand(await getLocale());
  return <main className="marketing-site">
    <MarketingEffects />
    <MarketingLanguage />
    <PublicNavigation />

    <section className="marketing-hero" id="home">
      <div className="hero-atmosphere" aria-hidden="true"><i /><i /><i /></div>
      <div className="hero-copy"><span className="marketing-kicker"><Sparkles size={15} /><span data-i18n="hero.kicker">Built for NGOs and compliance professionals</span></span><h1><span data-i18n="hero.line1">Every obligation.</span><br /><em data-i18n="hero.line2">One clear path to completion.</em></h1><p data-i18n="hero.description">Setu brings compliance schedules, team responsibilities, evidence, donor relationships and impact programmes into one secure operating workspace—so nothing important lives only in a spreadsheet or inbox.</p><div className="hero-actions"><Link className="marketing-button hero-primary" href="/signup"><span data-i18n="hero.create">Create your workspace</span> <ArrowRight size={17} /></Link><a className="marketing-button ghost hero-secondary" href="#platform"><span data-i18n="hero.explore">Explore the platform</span> <ChevronRight size={17} /></a></div><div className="hero-assurance"><span><Check size={15} /><span data-i18n="hero.tenant">Tenant-isolated records</span></span><span><Check size={15} /><span data-i18n="hero.audit">Auditable workflows</span></span><span><Check size={15} /><span data-i18n="hero.india">India-first configuration</span></span></div><div className="hero-proof"><article><strong data-i18n="hero.proof1">One view</strong><small data-i18n="hero.proof1body">Compliance, evidence and impact</small></article><article><strong data-i18n="hero.proof2">Clear ownership</strong><small data-i18n="hero.proof2body">Every task has accountability</small></article><article><strong data-i18n="hero.proof3">Audit ready</strong><small data-i18n="hero.proof3body">History stays traceable</small></article></div></div>
      <div className="product-preview" aria-label="Example compliance dashboard">
        <div className="preview-signal"><span><Activity size={15} /></span><div><small>LIVE CONTROL</small><strong>86% portfolio on track</strong></div><i /></div>
        <div className="preview-top"><span className="preview-logo"><ShieldCheck size={16} /></span><i /><i /><b>Portfolio overview</b><span className="preview-avatar">AD</span></div>
        <div className="preview-body"><aside><i className="active"><LayoutDashboard size={15} /></i><i><ClipboardCheck size={15} /></i><i><CalendarCheck size={15} /></i><i><FolderLock size={15} /></i><i><BarChart3 size={15} /></i></aside><div className="preview-content"><div className="preview-heading"><div><small>GOOD MORNING</small><strong>Your compliance control room</strong></div><span>All organizations⌄</span></div><div className="preview-metrics"><article><small>ACTIVE OBLIGATIONS</small><strong>48</strong><em>Across the portfolio</em></article><article><small>NEEDS ATTENTION</small><strong>07</strong><em>Owners notified</em></article><article><small>ON TRACK</small><strong>86%</strong><em>Current cycle</em></article></div><div className="preview-grid"><article className="preview-deadlines"><header><strong>Priority deadlines</strong><span>View all</span></header>{[["FCRA annual return", "High", "31 Dec"], ["Annual audit", "Review", "30 Sep"], ["80G renewal evidence", "Medium", "30 Nov"]].map((row) => <div key={row[0]}><i /><span><strong>{row[0]}</strong><small>Evidence and owner tracked</small></span><b>{row[1]}</b><em>{row[2]}</em></div>)}</article><article className="preview-health"><header><strong>Portfolio health</strong></header><div className="health-ring"><span>86<small>%</small></span></div><p>Compliance completion</p><footer><span><i />Complete</span><span><i />In progress</span><span><i />At risk</span></footer></article></div></div></div>
        <div className="preview-float preview-float-evidence"><FileCheck2 size={16} /><span><small>EVIDENCE CHECK</small><strong>Audit trail complete</strong></span><Check size={14} /></div>
        <div className="preview-float preview-float-deadline"><BellRing size={15} /><span><small>NEXT DEADLINE</small><strong>Owner notified early</strong></span></div>
      </div>
    </section>

    <section className="trust-strip"><span>Designed for</span><strong><Building2 size={18} />Trusts</strong><strong><Landmark size={18} />Societies</strong><strong><FileCheck2 size={18} />Section 8 companies</strong><strong><UsersRound size={18} />CA and consultant firms</strong></section>

    <section className="marketing-section intro" id="platform"><div className="section-heading"><span>THE PLATFORM</span><h2>A connected operating system for compliance work</h2><p>Setu follows the full operational lifecycle—from applicability and scheduling to filing proof, audit history and renewal.</p></div><div className="service-grid">{coreServices.map(({ icon: Icon, title, text }) => <article key={title}><span><Icon size={22} /></span><h3>{title}</h3><p>{text}</p><a href="#workflow">See how it works <ArrowRight size={14} /></a></article>)}</div></section>

    <section className="certificate-section" id="certificates"><div className="section-heading"><span>CERTIFICATES AND REGISTRATIONS</span><h2>Know what is valid, what is expiring and where the proof lives</h2><p>Setu does not issue government certificates. It gives your team a controlled record of certificate evidence, renewals, owners and history.</p></div><div className="certificate-grid">{certificateFeatures.map(({ icon: Icon, title, text }, index) => <article key={title}><b>0{index + 1}</b><span><Icon size={22} /></span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="certificate-assurance"><ShieldCheck size={18} /><span><strong>Evidence, not legal issuance</strong>Certificate data remains organization-scoped, permission-controlled and connected to its audit trail.</span><a href="#security">Review security <ArrowRight size={14} /></a></div></section>

    <section className="workflow-section" id="workflow"><div className="workflow-copy"><span>FROM REQUIREMENT TO RECORD</span><h2>A workflow your whole team can follow</h2><p>Keep the statutory deadline intact while your team works toward an earlier internal target. Every material change is recorded for management and audit review.</p><div className="workflow-note"><BellRing size={21} /><div><strong>Attention before escalation</strong><p>Daily automation identifies upcoming work, overdue tasks, expiring documents and completed obligations ready for the next cycle.</p></div></div></div><ol>{steps.map(([number, title, text]) => <li key={number}><b>{number}</b><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></section>

    <section className="dnd-section" id="dnd"><div className="dnd-visual"><span className="orbit one"><HeartHandshake size={24} /></span><span className="orbit two"><HandHeart size={22} /></span><span className="orbit three"><FileClock size={22} /></span><div><small>CONNECTED IMPACT RECORDS</small><strong>Donor</strong><strong>Donation</strong><strong>Reporting</strong></div></div><div className="dnd-copy"><span>D&amp;D MANAGEMENT</span><h2>Donor and Donation context beside compliance</h2><p>Track donor relationships, grant commitments, restricted-purpose context, milestones and reporting responsibilities in the same organization-scoped workspace.</p><ul><li><Check size={16} /><span><strong>Donor relationship records</strong>Maintain institutional or individual donor context, ownership and stewardship notes.</span></li><li><Check size={16} /><span><strong>Grant and donation obligations</strong>Connect commitments, utilization reporting and evidence deadlines to accountable owners.</span></li><li><Check size={16} /><span><strong>Impact portfolio visibility</strong>Review grants, CSR projects and volunteer programmes without mixing records across clients.</span></li></ul><p className="scope-note"><ShieldCheck size={16} />Setu manages operational records and evidence. Payment collection requires an approved payment provider and is not presented as active until configured.</p></div></section>

    <section className="project-section" id="projects"><div className="project-intro"><span>PROJECT AND PROGRAMME OPERATIONS</span><h2>From funding commitment to accountable delivery</h2><p>Bring projects into the same controlled workspace as compliance—without confusing programme progress with statutory completion.</p><Link className="marketing-button" href="/signup">Build your project workspace <ArrowRight size={16} /></Link></div><div className="project-grid">{projectFeatures.map(({ icon: Icon, label, title, text }, index) => <article key={label}><header><span><Icon size={19} /></span><small>{label}</small><b>0{index + 1}</b></header><h3>{title}</h3><p>{text}</p><i><b style={{ width: `${72 + index * 7}%` }} /></i><footer><span>{72 + index * 7}% example progress</span><strong>Owner tracked</strong></footer></article>)}</div></section>

    <section className="marketing-section solutions" id="solutions"><div className="section-heading"><span>WHO SETU SERVES</span><h2>One platform, different views of responsibility</h2></div><div className="solution-grid"><article><Building2 size={26} /><h3>NGOs</h3><p>Replace disconnected registers with a clear compliance calendar, evidence library and management dashboard.</p></article><article><Network size={26} /><h3>CA and consulting firms</h3><p>Switch safely between client organizations and monitor portfolio risk without cross-client confusion.</p></article><article><FileCheck2 size={26} /><h3>Auditors and reviewers</h3><p>Trace evidence versions, correction requests, completion history and filing acknowledgements.</p></article><article><HandHeart size={26} /><h3>CSR and programme teams</h3><p>Keep project milestones, grants, donors and volunteer activity connected to governance responsibilities.</p></article></div></section>

    <section className="capability-band"><div><span>CORE TODAY</span><h2>Everything needed to run the compliance cycle</h2><p>Organizations, catalogue rules, obligations, tasks, documents, notifications, audit, reports, memberships, entitlements and multi-client operations.</p></div><div><span>READY TO CONNECT</span><h2>Advanced services behind clean boundaries</h2><p>Email, WhatsApp, calendars, cloud drives, digital signatures, OCR, grounded AI, multilingual and white-label capabilities can be enabled as providers and plans are approved.</p></div></section>

    <section className="admin-section" id="admin"><div className="admin-copy"><span>ADMINISTRATION CONTROL CENTRE</span><h2>Configure the workspace without losing operational control</h2><p>The protected admin portal brings workspace governance, organization setup, user access, compliance catalogue rules, subscription limits, integrations and automation into one controlled area.</p><div className="admin-capabilities"><article><UserCog size={19} /><div><strong>Users and access</strong><small>Invite accounts, assign admin, member or viewer access, disable accounts and revoke existing sessions.</small></div></article><article><Building2 size={19} /><div><strong>Organizations and responsibilities</strong><small>Onboard legal entities, manage portfolio capacity and scope responsibility records to individual organizations.</small></div></article><article><SlidersHorizontal size={19} /><div><strong>Rules, plans and integrations</strong><small>Review versioned catalogue rules, entitlement usage and provider connection status.</small></div></article><article><Activity size={19} /><div><strong>Automation and audit</strong><small>Run idempotent daily operations and retain traceable records of material administration changes.</small></div></article></div><Link className="marketing-button" href="/admin/login"><KeyRound size={16} />Open admin portal <ArrowRight size={16} /></Link></div><div className="admin-preview" aria-label="Example admin control centre"><header><span><ShieldCheck size={16} />Administration</span><b>Business plan</b></header><div className="admin-preview-metrics"><article><small>ORGANIZATIONS</small><strong>3 / 10</strong><i><b style={{ width: "30%" }} /></i></article><article><small>TEAM ACCOUNTS</small><strong>8 / 25</strong><i><b style={{ width: "32%" }} /></i></article><article><small>ACTIVE RULES</small><strong>14</strong><em>Version controlled</em></article></div><section><div><strong>User management</strong><span>+ Invite user</span></div>{[["Ananya Desai", "Administrator", "Active"], ["Riya Mehta", "Team member", "Active"], ["Audit Reviewer", "Read-only viewer", "Invited"]].map((row) => <article key={row[0]}><i>{row[0].split(" ").map((part) => part[0]).join("").slice(0, 2)}</i><span><strong>{row[0]}</strong><small>Workspace account</small></span><b>{row[1]}</b><em>{row[2]}</em></article>)}</section><footer><ShieldCheck size={14} />Administrative actions are permission-controlled and audited.</footer></div></section>

    <section className="security-section" id="security"><div><span>SECURITY BY DESIGN</span><h2>Your organization boundary is enforced on the server</h2><p>Setu treats the tenant as the security and billing boundary and the organization as the client boundary inside it. Client-side controls improve usability; server-side authorization protects the records.</p><div className="security-list"><span><LockKeyhole size={18} />Strong sessions and protected mutations</span><span><ShieldCheck size={18} />Role-based, tenant-scoped access</span><span><FolderLock size={18} />Versioned evidence metadata</span><span><Cloud size={18} />Private-storage production path</span></div></div><aside><Bot size={26} /><h3>Human-reviewed intelligence</h3><p>The assistant summarizes authorized operational records, cites the records used and never presents itself as a legal authority or autonomously files compliance.</p><strong>Assistance with accountability.</strong></aside></section>

    <section className="marketing-section plans" id="plans"><div className="section-heading"><span>PLANS THAT SCALE WITH RESPONSIBILITY</span><h2>Start focused. Add capacity when you need it.</h2><p>Plan entitlements govern organizations, users, storage and advanced capabilities without deleting historical data.</p></div><div className="plan-grid">{plans.map((plan) => <article className={plan.featured ? "featured" : ""} key={plan.name}>{plan.featured && <span className="plan-tag">Most popular</span>}<h3>{plan.name}</h3><p>{plan.audience}</p><ul>{plan.features.map((feature) => <li key={feature}><Check size={15} />{feature}</li>)}</ul><Link href="/signup">Choose {plan.name} <ArrowRight size={15} /></Link></article>)}</div><p className="pricing-note">Commercial pricing, usage limits and provider charges are configured during deployment. No statutory deadline or legal rule is treated as professional advice.</p></section>

    <section className="faq-section" id="faq"><div className="section-heading"><span>COMMON QUESTIONS</span><h2>What organizations ask before they begin</h2></div><div className="faq-grid"><details open><summary>Does Setu file directly with government portals?</summary><p>Not by default. Setu manages the workflow, evidence and filing record. Direct portal integrations are enabled only where official interfaces and permissions exist.</p></details><details><summary>Can a consultant manage multiple NGO clients?</summary><p>Yes. Consultant workspaces can contain multiple organizations with organization switching, portfolio reporting and scoped access.</p></details><details><summary>Are compliance dates guaranteed legal advice?</summary><p>No. Catalogue rules and dates are versioned configuration and must be validated by qualified legal and compliance professionals.</p></details><details><summary>Does D&amp;D include payment collection?</summary><p>D&amp;D covers donor, grant, donation-context and reporting records. Payment collection requires a separately approved payment provider.</p></details><details><summary>Can Setu support regional languages?</summary><p>The platform architecture supports a multilingual roadmap. English is the current product language until translated content is reviewed and enabled.</p></details><details><summary>What happens when a subscription changes?</summary><p>Plan limits and feature access can change, but historical compliance and evidence records are not silently deleted.</p></details></div></section>

    <section className="support-section" id="support"><div><span>SUPPORT THE MISSION</span><h2>Help more NGOs move from missed follow-ups to accountable operations.</h2></div><div className="support-options"><article><strong>Partner with Setu</strong><p>Bring implementation, compliance or technology expertise to organizations that need it.</p><a href="#contact">Discuss a partnership <ArrowRight size={14} /></a></article><article><strong>Refer an organization</strong><p>Introduce an NGO or professional practice that is ready to organize its compliance work.</p><Link href="/signup">Create their workspace <ArrowRight size={14} /></Link></article><article><strong>Contribute expertise</strong><p>Help validate catalogue rules and operational guidance before they reach production teams.</p><a href="#contact">Start a conversation <ArrowRight size={14} /></a></article></div></section>

    <section className="final-cta" id="contact"><span><Languages size={19} />CONTACT AND ONBOARDING</span><h2>Give every compliance responsibility a clear owner, deadline and evidence trail.</h2><p>Create a workspace to begin onboarding, or sign in to continue with your existing NGO or professional practice.</p><div><Link className="marketing-button light" href="/signup">Request onboarding <ArrowRight size={17} /></Link><Link className="marketing-button outline-light" href="/login">Log in to Setu</Link></div></section>

    <footer className="marketing-footer"><div><Link className="marketing-brand" href="/">{brand.enabled ? <BrandIdentity /> : <><span><ShieldCheck size={21} /></span><strong>Setu NGO<small>Compliance and impact management</small></strong></>}</Link><p>{brand.enabled ? brand.description : "Operational software for NGO compliance teams and professional service providers."}</p>{brand.support_email && <a href={`mailto:${brand.support_email}`}>{brand.support_email}</a>}{brand.support_phone && <p>{brand.support_phone}</p>}{brand.support_url && <a href={brand.support_url} target="_blank" rel="noopener noreferrer">Support</a>}</div><div><strong>Platform</strong><a href="#platform">Compliance</a><a href="#dnd">D&amp;D</a><a href="#admin">Administration</a><a href="#security">Security</a><a href="#plans">Plans</a></div><div><strong>Access</strong><Link href="/login">Team login</Link><Link href="/admin/login">Admin login</Link><Link href="/signup">Create workspace</Link><Link href="/dashboard">Open dashboard</Link></div><div><strong>Important</strong><p>{brand.brand_name} supports compliance operations. It does not replace a CA, lawyer, auditor or official government portal.</p>{brand.privacy_url && <a href={brand.privacy_url} target="_blank" rel="noopener noreferrer">Privacy</a>}{brand.terms_url && <a href={brand.terms_url} target="_blank" rel="noopener noreferrer">Terms</a>}</div><small>{brand.footer_text || `© 2026 ${brand.brand_name}. All rights reserved.`}</small></footer>
  </main>;
}
