"use client";
import {useEffect,useState} from "react";
import {useTranslations} from "next-intl";
import {apiRequest} from "@/lib/http";
import type {AuthUser,InvitationResult} from "@/lib/auth-types";
import type {Membership} from "@/lib/types";
export default function OrganizationTeamEditor({id,allowed}:{id:string;allowed:boolean}){
 const t=useTranslations("Onboarding"),roles=useTranslations("ComplianceMaster"),statuses=useTranslations("Organization");const [accounts,setAccounts]=useState<AuthUser[]>([]),[memberships,setMemberships]=useState<Membership[]>([]),[mode,setMode]=useState("login"),[name,setName]=useState(""),[email,setEmail]=useState(""),[role,setRole]=useState("MEMBER"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[link,setLink]=useState(""),[saved,setSaved]=useState(false);
 async function refresh(){setBusy(true);setError("");try{const [a,m]=await Promise.all([apiRequest<AuthUser[]>("/admin/users"),apiRequest<Membership[]>("/memberships")]);setAccounts(a);setMemberships(m.filter(r=>r.organization_id===id||r.organization_id===null));}catch(e){setError(e instanceof Error?e.message:t("error"));}finally{setBusy(false);}}
 useEffect(()=>{if(allowed)void refresh();},[id,allowed]);
 async function invite(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setLink("");setSaved(false);try{if(mode==="login"){const result=await apiRequest<InvitationResult>("/admin/users/invite","POST",{name,email,role});setLink(window.location.origin+"/accept-invitation#token="+encodeURIComponent(result.token));}else await apiRequest("/memberships/invitations","POST",{organization_id:id,name,email,role});setName("");setEmail("");await refresh();setSaved(true);}catch(e){setError(e instanceof Error?e.message:t("error"));}finally{setBusy(false);}}
 if(!allowed)return <p>{t("readOnly")}</p>;
 return <><p>{t("loginHelp")}</p><p>{t("responsibilityHelp")}</p>{error&&<p role="alert" className="auth-alert error">{error}</p>}{saved&&<p role="status">{t("invited")}</p>}{link&&<p>{t("acceptLink")}: <a href={link}>{t("invite")}</a></p>}<h3>{t("loginAccounts")}</h3><ul className="organization-records">{accounts.map(a=><li key={a.id}>{a.name} ? {a.email} ? {t(a.role)} ? {statuses(a.status)}</li>)}</ul><h3>{t("responsibilityRecords")}</h3><ul className="organization-records">{memberships.map(m=><li key={m.id}>{m.name} ? {m.email} ? {roles("roles."+m.role)} ? {statuses(m.status)}</li>)}</ul><form onSubmit={e=>void invite(e)}><div className="organization-form"><label>{t("inviteType")}<select disabled={busy} value={mode} onChange={e=>{setMode(e.target.value);setRole(e.target.value==="login"?"MEMBER":"COMPLIANCE_OFFICER");}}><option value="login">{t("loginAccounts")}</option><option value="responsibility">{t("responsibilityRecords")}</option></select></label><label>{t("name")}<input required minLength={2} maxLength={120} disabled={busy} value={name} onChange={e=>setName(e.target.value)}/></label><label>{t("email")}<input type="email" required maxLength={200} disabled={busy} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>{t("role")}<select disabled={busy} value={role} onChange={e=>setRole(e.target.value)}>{(mode==="login"?["ADMIN","MEMBER","VIEWER"]:["TENANT_ADMIN","ORGANIZATION_ADMIN","COMPLIANCE_OFFICER","ACCOUNTANT","AUDITOR","CONSULTANT","MANAGEMENT","VIEWER"]).map(r=><option key={r} value={r}>{mode==="login"?t(r):roles("roles."+r)}</option>)}</select></label></div><div className="organization-actions"><button type="submit" className="button primary" disabled={busy}>{t("invite")}</button><button type="button" className="button secondary" disabled={busy} onClick={()=>void refresh()}>{t("refresh")}</button></div></form></>;
}
