import {test,expect,request as playwrightRequest} from "@playwright/test";
import {execFileSync,} from "node:child_process";
import {readFileSync} from "node:fs";
import path from "node:path";
import {newConfiguration} from "../../lib/compliance-master";
import {cleanSignupFixtureQuota,provisionPlatformOperator} from "./platform-operator";
const headers={"X-Setu-Request":"1"};
function token(email:string,purpose:"VERIFY") {
 const database=process.env.SETU_QA_DATABASE_URL;if(!database?.includes("setu-white-label-qa-"))throw new Error("Requires isolated QA database");
 const script=["import sys","from sqlalchemy import select","from app.database import SessionLocal","from app.models import User","from app.auth import issue_token","with SessionLocal() as db:"," user=db.scalar(select(User).where(User.email==sys.argv[1]))"," value=issue_token(db,user,sys.argv[2],1)"," db.commit()"," print(value)"].join("\n");
 return execFileSync(process.env.API_PYTHON||path.resolve("../api/.venv/Scripts/python.exe"),["-c",script,email,purpose],{cwd:path.resolve("../api"),env:{...process.env,DATABASE_URL:database},windowsHide:true}).toString().trim();
}
test("verified customer lifecycle uses real evidence and isolates two NGO workspaces",async({page,request,context})=>{
 cleanSignupFixtureQuota();const email="phase5-owner@example.test",password="Phase5-lifecycle-QA-2026!";
 expect((await request.post("/api/v1/auth/signup",{headers,data:{name:"Lifecycle owner",workspace_name:"Lifecycle workspace",email,password}})).status()).toBe(201);
 expect((await request.post("/api/v1/auth/verify-email",{headers,data:{token:token(email,"VERIFY")}})).ok()).toBeTruthy();
 expect((await request.post("/api/v1/auth/login",{headers,data:{email,password}})).ok()).toBeTruthy();
 const aResponse=await request.post("/api/v1/organizations",{headers,data:{name:"Lifecycle NGO A",legal_type:"TRUST",registration_number:"LIFECYCLE-A",city:"Lifecycle City",generate_compliance_plan:false}});expect(aResponse.status()).toBe(201);const ngoA=(await aResponse.json()).organization;
 const bResponse=await request.post("/api/v1/organizations",{headers,data:{name:"Lifecycle NGO B",legal_type:"SOCIETY",registration_number:"LIFECYCLE-B",city:"Second City",generate_compliance_plan:false}});expect(bResponse.status()).toBe(201);const ngoB=(await bResponse.json()).organization;
 expect((await request.post(`/api/v1/organizations/${ngoA.id}/onboarding/start`,{headers})).ok()).toBeTruthy();
 let saved=await request.patch(`/api/v1/organizations/${ngoA.id}/profile`,{headers,data:{expected_revision:0,core:{name:"Lifecycle NGO A",legal_type:"TRUST",registration_number:"LIFECYCLE-A",city:"Lifecycle City",status:"ACTIVE",pan:"ABCDE1234F"},details:{tan:"ABCD12345E",contact_name:"Lifecycle contact",contact_email:"contact@example.test",financial_year:"2026-27"},financial:{annual_revenue:"1250000.00",revenue_period:"2025-26"},registrations:[{kind:"12AB",status:"ACTIVE",number:"12AB-SAMPLE",expiry_date:"2031-03-31"},{kind:"80G",status:"ACTIVE",number:"80G-SAMPLE",expiry_date:"2031-03-31"},{kind:"FCRA",status:"NOT_REGISTERED"},{kind:"GST",status:"NOT_REGISTERED"},{kind:"CSR",status:"NOT_REGISTERED"}]}});expect(saved.ok()).toBeTruthy();
 const upload=await request.post("/api/v1/documents/upload",{headers,multipart:{metadata:JSON.stringify({request_id:crypto.randomUUID(),organization_id:ngoA.id,name:"Lifecycle proof.png",category:"Sample evidence",expiry_at:"2031-03-31"}),file:{name:"proof.png",mimeType:"image/png",buffer:readFileSync(path.resolve("tests/fixtures/proof.png"))}}});expect(upload.status()).toBe(201);const evidence=(await upload.json()).document;
 const invitation=await request.post("/api/v1/admin/users/invite",{headers,data:{name:"Lifecycle team member",email:"phase5-team@example.test",role:"MEMBER"}});expect(invitation.status()).toBe(201);const invitationToken=(await invitation.json()).token;
 const recipient=await playwrightRequest.newContext({baseURL:"http://localhost:3001",extraHTTPHeaders:headers});expect((await recipient.post("/api/v1/auth/accept-invitation",{data:{token:invitationToken,password:"Phase5-member-QA-2026!"}})).status()).toBe(204);await recipient.dispose();
 expect((await request.post("/api/v1/memberships/invitations",{headers,data:{organization_id:ngoA.id,name:"Lifecycle team member",email:"phase5-team@example.test",role:"COMPLIANCE_OFFICER"}})).status()).toBe(201);
 expect((await request.post("/api/v1/auth/logout",{headers})).status()).toBe(204);
 const operator={email:"white-label-qa@example.test",password:"WhiteLabel-browser-QA-2026!"};let login=await request.post("/api/v1/auth/login",{headers,data:operator});if(login.status()===401){expect((await request.post("/api/v1/auth/signup",{headers,data:{name:"Master QA",workspace_name:"Template QA",...operator}})).status()).toBe(201);}await provisionPlatformOperator(request);
 const category=await request.post("/api/v1/admin/compliance-categories",{headers,data:{name:"Lifecycle category"}});expect(category.status()).toBe(201);const configuration=newConfiguration();Object.assign(configuration,{name:"Lifecycle governance filing",category_id:(await category.json()).id,jurisdiction:"Sample jurisdiction",risk_level:"HIGH",priority:"HIGH"});configuration.responsibility={owner_role:"TENANT_ADMIN",fallback_role:"TENANT_ADMIN",reviewer_role:"TENANT_ADMIN",approver_role:"TENANT_ADMIN"};configuration.applicability={match_all:false,operator:"AND",groups:[{id:"customer",operator:"AND",conditions:[{id:"registration",field:"registration_number",operator:"EQUALS",value:"LIFECYCLE-A"}]}]};configuration.deadline={strategy:"FIXED_DATE",fixed_date:"2031-03-31",offset_days:0,internal_lead_days:15,document_type:"",event_key:""};
 const states=["NOT_STARTED","IN_PROGRESS","UNDER_REVIEW","CHANGES_REQUESTED","READY_TO_FILE","FILED","COMPLETED"];
 configuration.workflow={stages:states.map((state,index)=>({id:`stage-${index}`,state,label:""})),transitions:states.slice(1).map((to,index)=>({from_state:states[index],to_state:to,allowed_roles:["TENANT_ADMIN"],required_evidence:["UNDER_REVIEW","FILED","COMPLETED"].includes(to),required_approval:["READY_TO_FILE","COMPLETED"].includes(to)})).concat([{from_state:"CHANGES_REQUESTED",to_state:"IN_PROGRESS",allowed_roles:["TENANT_ADMIN"],required_evidence:false,required_approval:false},{from_state:"UNDER_REVIEW",to_state:"READY_TO_FILE",allowed_roles:["TENANT_ADMIN"],required_evidence:false,required_approval:true}])};configuration.checklist=[{id:"review-evidence",title:"Review filed evidence",description:"",instructions:"",required:true,responsible_role:"COMPLIANCE_OFFICER",relative_due_days:-7}];configuration.documents=[{id:"original-proof",document_type:"Sample evidence",required:true,minimum_count:1,must_be_valid:true,instructions:""}];
 let template=await request.post("/api/v1/admin/compliance-templates",{headers,data:{code:"LIFECYCLE-E2E",configuration}});expect(template.status()).toBe(201);let row=await template.json();for(const action of ["submit-review","approve","publish"]){const response=await request.post(`/api/v1/admin/compliance-templates/${row.id}/${action}`,{headers,data:{expected_revision:row.revision}});expect(response.ok()).toBeTruthy();row=await response.json();}
 expect((await request.post("/api/v1/auth/logout",{headers})).status()).toBe(204);expect((await request.post("/api/v1/auth/login",{headers,data:{email,password}})).ok()).toBeTruthy();
 let progress=(await (await request.get(`/api/v1/organizations/${ngoA.id}/onboarding`)).json()).state;for(const current_step of ["registration","compliance","financial","documents","team","review","evaluation"]){const response=await request.patch(`/api/v1/organizations/${ngoA.id}/onboarding`,{headers,data:{expected_revision:progress.revision,current_step,complete_step:true}});expect(response.ok()).toBeTruthy();progress=(await response.json()).state;}
 const evaluation=await request.post(`/api/v1/organizations/${ngoA.id}/onboarding/evaluate`,{headers});expect(evaluation.ok()).toBeTruthy();expect((await evaluation.json()).results.find((r:{code:string})=>r.code==="LIFECYCLE-E2E").effective_result).toBe("APPLICABLE");
 const complete=await request.post(`/api/v1/organizations/${ngoA.id}/onboarding/complete`,{headers,data:{expected_revision:progress.revision}});expect(complete.ok()).toBeTruthy();const generatedIds=(await complete.json()).generated_ids;const generated=(await (await request.get("/api/v1/compliances")).json()).filter((c:{id:string})=>generatedIds.includes(c.id));const complianceId=generated.find((c:{code:string})=>c.code==="LIFECYCLE-E2E").id;
 const candidate=await (await request.get(`/api/v1/compliances/${complianceId}/owner-candidates`)).json();const owner=candidate.find((u:{name:string})=>u.name==="Lifecycle owner");expect(owner).toBeTruthy();const beforeOwner=await (await request.get(`/api/v1/compliances/${complianceId}/runtime-detail`)).json();const assignment=await request.post(`/api/v1/compliances/${complianceId}/owner`,{headers,data:{owner_id:owner.id,expected_owner_id:beforeOwner.owner?.owner_id||null,reason:"Confirm lifecycle ownership"}});expect(assignment.ok(),await assignment.text()).toBeTruthy();
 const detail=await (await request.get(`/api/v1/compliances/${complianceId}/runtime-detail`)).json();expect(detail.tasks).toHaveLength(1);expect(detail.snapshot.documents[0].document_ids).toContain(evidence.id);
 const transition=async(target_status:string,extra:Record<string,string>={})=>{const result=await request.post(`/api/v1/compliances/${complianceId}/transitions`,{headers,data:{target_status,...extra}});expect(result.ok(),await result.text()).toBeTruthy();};
 await transition("IN_PROGRESS");await transition("UNDER_REVIEW",{proof_document_id:evidence.id});await transition("CHANGES_REQUESTED",{reason:"Reviewer correction requested"});await transition("IN_PROGRESS");await transition("UNDER_REVIEW",{proof_document_id:evidence.id});await transition("READY_TO_FILE");await transition("FILED",{proof_document_id:evidence.id,submission_reference:"LIFECYCLE-FILING-001"});expect((await request.patch(`/api/v1/tasks/${detail.tasks[0].id}`,{headers,data:{status:"DONE"}})).ok()).toBeTruthy();await transition("COMPLETED",{proof_document_id:evidence.id});
 await context.addCookies((await request.storageState()).cookies);const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));await page.goto(`/compliances/${complianceId}`);await expect(page.getByRole("heading",{name:"Lifecycle governance filing",exact:true,level:1})).toBeVisible();await expect(page.getByText("LIFECYCLE-FILING-001",{exact:false})).toBeVisible();await expect(page.getByRole("link",{name:"Download filed original"})).toBeVisible();for(const width of [320,768,1024,1440]){await page.setViewportSize({width,height:1000});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();}expect(errors).toEqual([]);
 const other=await playwrightRequest.newContext({baseURL:"http://localhost:3001",extraHTTPHeaders:headers});cleanSignupFixtureQuota();const otherEmail="phase5-other@example.test";expect((await other.post("/api/v1/auth/signup",{data:{name:"Other consultant",workspace_name:"Other workspace",email:otherEmail,password:"Phase5-other-QA-2026!"}})).status()).toBe(201);expect((await other.post("/api/v1/auth/verify-email",{data:{token:token(otherEmail,"VERIFY")}})).ok()).toBeTruthy();expect((await other.post("/api/v1/auth/login",{data:{email:otherEmail,password:"Phase5-other-QA-2026!"}})).ok()).toBeTruthy();
 expect((await other.get(`/api/v1/compliances/${complianceId}/runtime-detail`)).status()).toBe(404);expect((await other.get(`/api/v1/documents/${evidence.id}/content`)).status()).toBe(404);expect((await other.get(`/api/v1/organizations/${ngoA.id}/profile`)).status()).toBe(404);expect((await other.get(`/api/v1/organizations/${ngoB.id}/profile`)).status()).toBe(404);await other.dispose();
});
